Collection(6) [Map] {
       '878353335852339251' => Role {
         guild: Guild {
           id: '633535718559580179',
           name: 'r/realme Community',
           icon: 'a3a849a8dbebe078f8f71fdbf939b482',
           features: [Array],
           commands: [GuildApplicationCommandManager],
           members: [GuildMemberManager],
           channels: [GuildChannelManager],
           bans: [GuildBanManager],
           roles: [RoleManager],
           presences: PresenceManager {},
           voiceStates: [VoiceStateManager],
           stageInstances: [StageInstanceManager],
           invites: [GuildInviteManager],
           scheduledEvents: [GuildScheduledEventManager],
           available: true,
           shardId: 0,
           splash: null,
           banner: null,
           description: 'Discussion about the realme Smartphones and IoTs!',
           verificationLevel: 'MEDIUM',
           vanityURLCode: null,
           nsfwLevel: 'DEFAULT',
           discoverySplash: 'eb9fa406898b571dd64400621476e926',
           memberCount: 2965,
           large: true,
           premiumProgressBarEnabled: true,
           applicationId: null,
           afkTimeout: 900,
           afkChannelId: '878360684734328852',
           systemChannelId: '633539144013840384',
           premiumTier: 'NONE',
           premiumSubscriptionCount: 0,
           explicitContentFilter: 'ALL_MEMBERS',
           mfaLevel: 'ELEVATED',
           joinedTimestamp: 1648125170065,
           defaultMessageNotifications: 'ONLY_MENTIONS',
           systemChannelFlags: [SystemChannelFlags],
           maximumMembers: 500000,
           maximumPresences: null,
           approximateMemberCount: null,
           approximatePresenceCount: null,
           vanityURLUses: null,
           rulesChannelId: '888030453574029352',
           publicUpdatesChannelId: '742980169702309919',
           preferredLocale: 'en-US',
           ownerId: '767729995749523476',
           emojis: [GuildEmojiManager],
           stickers: [GuildStickerManager]
         },
         icon: null,
         unicodeEmoji: null,
         id: '878353335852339251',
         name: 'DART',
         color: 3447003,
         hoist: false,
         rawPosition: 27,
         permissions: Permissions { bitfield: 0n },
         managed: false,
         mentionable: false,
         tags: {}
       },
       '848900950919741480' => Role {
         guild: Guild {
           id: '633535718559580179',
           name: 'r/realme Community',
           icon: 'a3a849a8dbebe078f8f71fdbf939b482',
           features: [Array],
           commands: [GuildApplicationCommandManager],
           members: [GuildMemberManager],
           channels: [GuildChannelManager],
           bans: [GuildBanManager],
           roles: [RoleManager],
           presences: PresenceManager {},
           voiceStates: [VoiceStateManager],
           stageInstances: [StageInstanceManager],
           invites: [GuildInviteManager],
           scheduledEvents: [GuildScheduledEventManager],
           available: true,
           shardId: 0,
           splash: null,
           banner: null,
           description: 'Discussion about the realme Smartphones and IoTs!',
           verificationLevel: 'MEDIUM',
           vanityURLCode: null,
           nsfwLevel: 'DEFAULT',
           discoverySplash: 'eb9fa406898b571dd64400621476e926',
           memberCount: 2965,
           large: true,
           premiumProgressBarEnabled: true,
           applicationId: null,
           afkTimeout: 900,
           afkChannelId: '878360684734328852',
           systemChannelId: '633539144013840384',
           premiumTier: 'NONE',
           premiumSubscriptionCount: 0,
           explicitContentFilter: 'ALL_MEMBERS',
           mfaLevel: 'ELEVATED',
           joinedTimestamp: 1648125170065,
           defaultMessageNotifications: 'ONLY_MENTIONS',
           systemChannelFlags: [SystemChannelFlags],
           maximumMembers: 500000,
           maximumPresences: null,
           approximateMemberCount: null,
           approximatePresenceCount: null,
           vanityURLUses: null,
           rulesChannelId: '888030453574029352',
           publicUpdatesChannelId: '742980169702309919',
           preferredLocale: 'en-US',
           ownerId: '767729995749523476',
           emojis: [GuildEmojiManager],
           stickers: [GuildStickerManager]
         },
         icon: null,
         unicodeEmoji: null,
         id: '848900950919741480',
         name: 'Member',
         color: 12745742,
         hoist: true,
         rawPosition: 25,
         permissions: Permissions { bitfield: 137506327553n },
         managed: false,
         mentionable: false,
         tags: {}
       },
       '633540556164694026' => Role {
         guild: Guild {
           id: '633535718559580179',
           name: 'r/realme Community',
           icon: 'a3a849a8dbebe078f8f71fdbf939b482',
           features: [Array],
           commands: [GuildApplicationCommandManager],
           members: [GuildMemberManager],
           channels: [GuildChannelManager],
           bans: [GuildBanManager],
           roles: [RoleManager],
           presences: PresenceManager {},
           voiceStates: [VoiceStateManager],
           stageInstances: [StageInstanceManager],
           invites: [GuildInviteManager],
           scheduledEvents: [GuildScheduledEventManager],
           available: true,
           shardId: 0,
           splash: null,
           banner: null,
           description: 'Discussion about the realme Smartphones and IoTs!',
           verificationLevel: 'MEDIUM',
           vanityURLCode: null,
           nsfwLevel: 'DEFAULT',
           discoverySplash: 'eb9fa406898b571dd64400621476e926',
           memberCount: 2965,
           large: true,
           premiumProgressBarEnabled: true,
           applicationId: null,
           afkTimeout: 900,
           afkChannelId: '878360684734328852',
           systemChannelId: '633539144013840384',
           premiumTier: 'NONE',
           premiumSubscriptionCount: 0,
           explicitContentFilter: 'ALL_MEMBERS',
           mfaLevel: 'ELEVATED',
           joinedTimestamp: 1648125170065,
           defaultMessageNotifications: 'ONLY_MENTIONS',
           systemChannelFlags: [SystemChannelFlags],
           maximumMembers: 500000,
           maximumPresences: null,
           approximateMemberCount: null,
           approximatePresenceCount: null,
           vanityURLUses: null,
           rulesChannelId: '888030453574029352',
           publicUpdatesChannelId: '742980169702309919',
           preferredLocale: 'en-US',
           ownerId: '767729995749523476',
           emojis: [GuildEmojiManager],
           stickers: [GuildStickerManager]
         },
         icon: null,
         unicodeEmoji: null,
         id: '633540556164694026',
         name: 'Discord Mod',
         color: 15844367,
         hoist: true,
         rawPosition: 53,
         permissions: Permissions { bitfield: 541165879295n },
         managed: false,
         mentionable: true,
         tags: {}
       },
       '878353559308087326' => Role {
         guild: Guild {
           id: '633535718559580179',
           name: 'r/realme Community',
           icon: 'a3a849a8dbebe078f8f71fdbf939b482',
           features: [Array],
           commands: [GuildApplicationCommandManager],
           members: [GuildMemberManager],
           channels: [GuildChannelManager],
           bans: [GuildBanManager],
           roles: [RoleManager],
           presences: PresenceManager {},
           voiceStates: [VoiceStateManager],
           stageInstances: [StageInstanceManager],
           invites: [GuildInviteManager],
           scheduledEvents: [GuildScheduledEventManager],
           available: true,
           shardId: 0,
           splash: null,
           banner: null,
           description: 'Discussion about the realme Smartphones and IoTs!',
           verificationLevel: 'MEDIUM',
           vanityURLCode: null,
           nsfwLevel: 'DEFAULT',
           discoverySplash: 'eb9fa406898b571dd64400621476e926',
           memberCount: 2965,
           large: true,
           premiumProgressBarEnabled: true,
           applicationId: null,
           afkTimeout: 900,
           afkChannelId: '878360684734328852',
           systemChannelId: '633539144013840384',
           premiumTier: 'NONE',
           premiumSubscriptionCount: 0,
           explicitContentFilter: 'ALL_MEMBERS',
           mfaLevel: 'ELEVATED',
           joinedTimestamp: 1648125170065,
           defaultMessageNotifications: 'ONLY_MENTIONS',
           systemChannelFlags: [SystemChannelFlags],
           maximumMembers: 500000,
           maximumPresences: null,
           approximateMemberCount: null,
           approximatePresenceCount: null,
           vanityURLUses: null,
           rulesChannelId: '888030453574029352',
           publicUpdatesChannelId: '742980169702309919',
           preferredLocale: 'en-US',
           ownerId: '767729995749523476',
           emojis: [GuildEmojiManager],
           stickers: [GuildStickerManager]
         },
         icon: null,
         unicodeEmoji: null,
         id: '878353559308087326',
         name: 'SuperDART',
         color: 1752220,
         hoist: false,
         rawPosition: 28,
         permissions: Permissions { bitfield: 0n },
         managed: false,
         mentionable: false,
         tags: {}
       },
       '791317512485732362' => Role {
         guild: Guild {
           id: '633535718559580179',
           name: 'r/realme Community',
           icon: 'a3a849a8dbebe078f8f71fdbf939b482',
           features: [Array],
           commands: [GuildApplicationCommandManager],
           members: [GuildMemberManager],
           channels: [GuildChannelManager],
           bans: [GuildBanManager],
           roles: [RoleManager],
           presences: PresenceManager {},
           voiceStates: [VoiceStateManager],
           stageInstances: [StageInstanceManager],
           invites: [GuildInviteManager],
           scheduledEvents: [GuildScheduledEventManager],
           available: true,
           shardId: 0,
           splash: null,
           banner: null,
           description: 'Discussion about the realme Smartphones and IoTs!',
           verificationLevel: 'MEDIUM',
           vanityURLCode: null,
           nsfwLevel: 'DEFAULT',
           discoverySplash: 'eb9fa406898b571dd64400621476e926',
           memberCount: 2965,
           large: true,
           premiumProgressBarEnabled: true,
           applicationId: null,
           afkTimeout: 900,
           afkChannelId: '878360684734328852',
           systemChannelId: '633539144013840384',
           premiumTier: 'NONE',
           premiumSubscriptionCount: 0,
           explicitContentFilter: 'ALL_MEMBERS',
           mfaLevel: 'ELEVATED',
           joinedTimestamp: 1648125170065,
           defaultMessageNotifications: 'ONLY_MENTIONS',
           systemChannelFlags: [SystemChannelFlags],
           maximumMembers: 500000,
           maximumPresences: null,
           approximateMemberCount: null,
           approximatePresenceCount: null,
           vanityURLUses: null,
           rulesChannelId: '888030453574029352',
           publicUpdatesChannelId: '742980169702309919',
           preferredLocale: 'en-US',
           ownerId: '767729995749523476',
           emojis: [GuildEmojiManager],
           stickers: [GuildStickerManager]
         },
         icon: null,
         unicodeEmoji: null,
         id: '791317512485732362',
         name: 'realme 7 Series',
         color: 0,
         hoist: false,
         rawPosition: 19,
         permissions: Permissions { bitfield: 0n },
         managed: false,
         mentionable: false,
         tags: {}
       },
       '633535718559580179' => Role {
         guild: Guild {
           id: '633535718559580179',
           name: 'r/realme Community',
           icon: 'a3a849a8dbebe078f8f71fdbf939b482',
           features: [Array],
           commands: [GuildApplicationCommandManager],
           members: [GuildMemberManager],
           channels: [GuildChannelManager],
           bans: [GuildBanManager],
           roles: [RoleManager],
           presences: PresenceManager {},
           voiceStates: [VoiceStateManager],
           stageInstances: [StageInstanceManager],
           invites: [GuildInviteManager],
           scheduledEvents: [GuildScheduledEventManager],
           available: true,
           shardId: 0,
           splash: null,
           banner: null,
           description: 'Discussion about the realme Smartphones and IoTs!',
           verificationLevel: 'MEDIUM',
           vanityURLCode: null,
           nsfwLevel: 'DEFAULT',
           discoverySplash: 'eb9fa406898b571dd64400621476e926',
           memberCount: 2965,
           large: true,
           premiumProgressBarEnabled: true,
           applicationId: null,
           afkTimeout: 900,
           afkChannelId: '878360684734328852',
           systemChannelId: '633539144013840384',
           premiumTier: 'NONE',
           premiumSubscriptionCount: 0,
           explicitContentFilter: 'ALL_MEMBERS',
           mfaLevel: 'ELEVATED',
           joinedTimestamp: 1648125170065,
           defaultMessageNotifications: 'ONLY_MENTIONS',
           systemChannelFlags: [SystemChannelFlags],
           maximumMembers: 500000,
           maximumPresences: null,
           approximateMemberCount: null,
           approximatePresenceCount: null,
           vanityURLUses: null,
           rulesChannelId: '888030453574029352',
           publicUpdatesChannelId: '742980169702309919',
           preferredLocale: 'en-US',
           ownerId: '767729995749523476',
           emojis: [GuildEmojiManager],
           stickers: [GuildStickerManager]
         },
         icon: null,
         unicodeEmoji: null,
         id: '633535718559580179',
         name: '@everyone',
         color: 0,
         hoist: false,
         rawPosition: 0,
         permissions: Permissions { bitfield: 0n },
         managed: false,
         mentionable: false,
         tags: {}
       }
     }